import com.simbirsoft.drools.clienthandler.model.DroolsClient
import com.simbirsoft.drools.clienthandler.model.ClientResult
import com.simbirsoft.drools.clienthandler.model.Subscriber
import java.util.List

rule "isBigClient"
when
    $client: DroolsClient(client.subscribers != null)
then
    ClientResult clientResult = $client.getClientResult();
    clientResult.setBig($client.getClient().getSubscribers().size() > 100);
end

rule "sumSubscribersSpent"
  when
    $client: DroolsClient(client.subscribers != null)
  then
    List<Subscriber> subscribers = $client.getClient().getSubscribers();
    long sum =0;
    for (Subscriber subscriber : subscribers) {
      sum+=subscriber.getSpent();
    }
    ClientResult clientResult = $client.getClientResult();
    clientResult.setSpentTotal(sum);
end