package rules

import org.slf4j.LoggerFactory
import com.simbirsoft.drools.clienthandler.model.DroolsClient
import com.simbirsoft.drools.clienthandler.model.ClientResult
import com.simbirsoft.drools.clienthandler.model.Subscriber

rule "Sum subscribers spent"
  when
    $droolsClient: DroolsClient($client: client, $clientResult: clientResult);
    $total : Number() from accumulate(
           s: Subscriber() from $client.subscribers,
           sum(s.getSpent()))
  then
    $clientResult.setSpentTotal($total.longValue());
  end

rule "Is big client"
  when
    $client: DroolsClient(client.subscribers != null && client.subscribers.size() > 100)
  then
    $client.getClientResult().setBig(true);
  end

rule "Unknown type"
  when
    not DroolsClient()
    some: Object()
  then
    LoggerFactory.getLogger(DroolsClient.class).warn("Waited DroolsClient. Recive: " + some);
  end