package rules

import com.simbirsoft.drools.clienthandler.model.DroolsClient
import com.simbirsoft.drools.clienthandler.model.ClientResult
import com.simbirsoft.drools.clienthandler.model.Subscriber
import function com.simbirsoft.drools.clienthandler.util.DroolsLogger.warn
import function com.simbirsoft.drools.clienthandler.util.DroolsLogger.error

rule "Is valid Client"
  when
    exists DroolsClient()
    $client: DroolsClient(client.subscribers == null)
  then
    error("Validation Error. Client subscribes is empty");
  end

rule "Sum subscribers spent"
  when
    exists DroolsClient()
    $droolsClient: DroolsClient($client: client, $clientResult: clientResult);
    $total : Number() from accumulate(
           s: Subscriber() from $client.subscribers,
           sum(s.getSpent()))
  then
    $clientResult.setSpentTotal($total.longValue());
  end

rule "Is big client"
  when
    exists DroolsClient()
    $client: DroolsClient(client.subscribers != null && client.subscribers.size() > 100)
  then
    $client.getClientResult().setBig(true);
  end

rule "Unknown type"
  when
    not DroolsClient()
    some: Object()
  then
    warn("Waited DroolsClient. Recive: " + some);
  end